// <auto-generated />
using System;
using EvidencePojisteni;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidencePojisteni.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20250729163843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("EvidencePojisteni.PojistenaOsoba", b =>
                {
                    b.Property<int>("CisloPojistence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vek")
                        .HasColumnType("INTEGER");

                    b.HasKey("CisloPojistence");

                    b.ToTable("PojisteneOsoby");
                });

            modelBuilder.Entity("EvidencePojisteni.Pojisteni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Castka")
                        .HasColumnType("TEXT");

                    b.Property<int>("CisloPojistence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlatnostDo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlatnostOd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Predmet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CisloPojistence");

                    b.ToTable("Pojisteni");
                });

            modelBuilder.Entity("EvidencePojisteni.Pojisteni", b =>
                {
                    b.HasOne("EvidencePojisteni.PojistenaOsoba", "PojistenaOsoba")
                        .WithMany("Pojisteni")
                        .HasForeignKey("CisloPojistence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PojistenaOsoba");
                });

            modelBuilder.Entity("EvidencePojisteni.PojistenaOsoba", b =>
                {
                    b.Navigation("Pojisteni");
                });
#pragma warning restore 612, 618
        }
    }
}
